### ISSUE TITLE
only Google logo is visible in the map

### ISSUE THREAD

**Issue by surbhitrao** [gawdsnitkkr/sell-my-services-android#1]
Hi on building the app and running it on my device in the map activity only google logo is visible. I tried putting the new API key but to no avail.

**Comment by varunon9** [comment]
Two things need to be followed-
1. Replace API key with your own API key
2. In Google API console, put the SHA signature of your debug/release version. 

To generate the SHA fingerprint - https://stackoverflow.com/questions/15727912/sha-1-fingerprint-of-keystore-certificate
To update SHA in API console- https://developers.google.com/maps/documentation/android-sdk/signup
