### ISSUE TITLE
Google sign in

### ISSUE THREAD

**Issue by surbhitrao** [gawdsnitkkr/sell-my-services-android#2]
I'm not able to sign in via Google. Am I missing any setup?

**Comment by varunon9** [comment]
Are you using your own backend?

**Comment by surbhitrao** [comment]
No.

**Comment by varunon9** [comment]
https://github.com/gawdsnitkkr/sell-my-services-backend/blob/master/config/config-sample.js here we are using our own `googleSigninClientId` so it won't work with your google oauth ApI Key. You need to have your own backend
